theme = "onedark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["diagnostics", "selections", "position","position-percentage", "file-encoding"]

[editor.lsp]
# auto-signature-help = true

[keys.normal]
# C-space = "signature_help"
a = ["append_mode", "collapse_selection"]

[keys.select]
"A-," = "flip_selections"

[keys.insert]
C-s = ":w"
C-q = "collapse_selection"
C-space = "signature_help"

[keys.normal.space]
w = ":update"
e = ":bprev"
q = ":quit"

S-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
S-d = [":new", ":insert-output lazydocker", ":buffer-close!", ":redraw"]
S-y = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]
